# -*- coding: utf-8 -*-
"""Gulfum_1st_cybersecurity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Hlw0w9uI1sarY7TlepiC5udmV5qklRt
"""

QUESTION :5

def household():
  print("\nCalculating household Eb price")
  unit=int(input("\nNumber of Units used: "))

  if unit<100:
    price=unit*0.50
    print("Your Price : Rs.",price)
  elif unit>101 and unit<200:
    price=unit*0.75
    print("Your Price : Rs.",price)
  elif unit>201 and unit<300:
    price=unit*1.20
    print("Your Price : Rs.",price)
  else:
    price=unit*1.50
    print("Your Price : Rs.",price)

household()

QUESTION : 1

print("""I am signing up for Replit's 100 days of Python challenge! I will make sure to spend
some time every day coding along, for a minimum of 10 minutes a day. I'll be using
Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.
No excuses for not coding from the middle of a field!""")

malware={'adwar':'tracks user activity',
        'Botnet':'infected and commanded by the attacker',
        'keylogger':'A keylogger can monitor a great deal of user activity, including email, browsing activity, program ',
        'spyware':'A little like adware'}
print(malware)
print(len(malware))
print(type(malware))
malware['trojon']='trojon is a malware it attack unexpeted time'
print(malware)
malware.update({'adwar':'virus'})
print(malware)
malware.pop('spyware')
print(malware)
malware.clear()
print(malware)

QUESTION :2

print("A person bought a mobile for the cost of 12,300 with additionally he pays 18% of GST.")
price=12300
GST=price*(18/100)
NetPrice=price+GST
print("GST",GST)
print("NetPrice:",NetPrice)

QUESTION:4

import pandas as pd
student_data=pd.DataFrame(
    {"Student_Name": ["gulfum", "Viggu", "Yogesh", "sai", "viggu", "manu", "vardan", "santosh", "satish", "peri"],
     "Age": [20,21,21,21,22,24,22,21,20,20],
     "DOB(year)": [2001,2000,2000,2000,1999,1997,1999,2000,2001,2001],
     "Weight(kg)" : [57,64,70,80,88,61,77,89,79,76],
     "Height(cm)" : [145,127,135,177,156,188,199,154,177,133]}
)

student_data["BMI"]=student_data["Weight(kg)"]/student_data["Height(cm)"]*student_data["Height(cm)"]

student_data["Status"]=student_data["BMI"].apply(lambda x: "Normal" if x>50 and x<80 else "Underweight")
# print(student_data)


student_data.to_csv("student_data.csv")
student_data=pd.read_csv("/content/student_data.csv")
student_data

QUESTION:3

import pandas as pd
crime=pd.DataFrame(
    {"Offense": ["Sending threatning messages by email", "Sending Defarmatory messages by email", "Forgery of electronic records", "Bogus websites,Cyber frauds", "Email Spoofing", "Web-Jacking", "E-Mail Abuse", "Online sale drugs", "Online sale of arms"],
     "IP Section(law)": [503,499,463,420,463,383,500,1985,1959],
     "Penalty(Rs)": [15000,15000,100000,20000,15000,30000,25000,200000,500000],
     "Crime in Popular apps" : ["Gmail,Outlook","Gmail,Outlook","OLX,Flipkart,Amazon","Gpay,Phonepe", "Gmail,Outlook", "Facebook,Instagram", "Gmail,Outlook","OLX,Facebook,Instagram","Flipkart,Amazon,Shop101"]}
)


crime





