# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGENjvTtN2t2Ho2SzDXV4X6DZaIMyKlq
"""

#Data type;Integer,Decimal,Boolean
my_integer=1233
print(type(my_integer))

dt_a=224
dt_a
print(dt_a)
type(dt_a)

dt_str=("data analysists")
type(dt_str)

dt_num=15
dt_dec=15.5
sum=dt_num+dt_dec
print(sum)
print(type(sum))

a="10"
b="copy"
c=a+b
print(c)

a=("My Name is Gulfum")
b
print(a.upper())
print(b.lower())

my_string="i hate you"
my_string.upper()

my_string="i hate you to"
my_string.lower()
my_string.find("hate")
my_string.replace("i","you")



print(float(dt_a))

print(float(dt_a))
print(int(dt_a))

a="2234"
int(a)

print(43/60*16-41)

min=160
hours=160/60
print(hours)

list1=["apple","oranges","500","sun"]
print(len(list1))
print(list1[2])
print(list1[2:4])

list1.extend([4,5])
print(list1)

del(list1[-3])
print(list1)

list1=("gulfum","yogesh","sandu","suresh")
bg=("o","a+","o-","b")
add=list1+bg
print(add)

tup=(1,2,("abhi","anu"),(29,6),("msc",22))
print(tup[2][1][0])
print(tup)

wa_corpa={"good":"bat","ball":"stumps"}
print(wa_corpa.keys())
print(wa_corpa.values())
# print(wa_corpa.keys{ball})
del(wa_corpa["good"])
print(wa_corpa)